# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Sat Feb 14 19:55:33 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/logo/logo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self._centralwidget = QtGui.QWidget(MainWindow)
        self._centralwidget.setObjectName("_centralwidget")
        MainWindow.setCentralWidget(self._centralwidget)
        self._menubar = QtGui.QMenuBar(MainWindow)
        self._menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self._menubar.setObjectName("_menubar")
        self._menu_program = QtGui.QMenu(self._menubar)
        self._menu_program.setObjectName("_menu_program")
        self._menu_view = QtGui.QMenu(self._menubar)
        self._menu_view.setObjectName("_menu_view")
        self._menu_help = QtGui.QMenu(self._menubar)
        self._menu_help.setObjectName("_menu_help")
        self._menu_action = QtGui.QMenu(self._menubar)
        self._menu_action.setObjectName("_menu_action")
        MainWindow.setMenuBar(self._menubar)
        self._statusbar = QtGui.QStatusBar(MainWindow)
        self._statusbar.setObjectName("_statusbar")
        MainWindow.setStatusBar(self._statusbar)
        self._toolbar = QtGui.QToolBar(MainWindow)
        self._toolbar.setObjectName("_toolbar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self._toolbar)
        self._action_quit = QtGui.QAction(MainWindow)
        self._action_quit.setObjectName("_action_quit")
        self._action_info = QtGui.QAction(MainWindow)
        self._action_info.setObjectName("_action_info")
        self._action_user_Details = QtGui.QAction(MainWindow)
        self._action_user_Details.setCheckable(True)
        self._action_user_Details.setChecked(True)
        self._action_user_Details.setObjectName("_action_user_Details")
        self._action_set_cols = QtGui.QAction(MainWindow)
        self._action_set_cols.setObjectName("_action_set_cols")
        self._action_delete = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self._action_delete.setIcon(icon1)
        self._action_delete.setObjectName("_action_delete")
        self._action_destroy_clipboard = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/destroy_clipboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self._action_destroy_clipboard.setIcon(icon2)
        self._action_destroy_clipboard.setObjectName("_action_destroy_clipboard")
        self._action_destroy_trash = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/destroy_trash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self._action_destroy_trash.setIcon(icon3)
        self._action_destroy_trash.setObjectName("_action_destroy_trash")
        self._action_lock = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/lock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self._action_lock.setIcon(icon4)
        self._action_lock.setObjectName("_action_lock")
        self._action_unlock = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/unlock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self._action_unlock.setIcon(icon5)
        self._action_unlock.setObjectName("_action_unlock")
        self._menu_program.addAction(self._action_quit)
        self._menu_view.addAction(self._action_user_Details)
        self._menu_view.addSeparator()
        self._menu_view.addAction(self._action_set_cols)
        self._menu_help.addAction(self._action_info)
        self._menu_action.addAction(self._action_lock)
        self._menu_action.addAction(self._action_unlock)
        self._menu_action.addSeparator()
        self._menu_action.addAction(self._action_destroy_clipboard)
        self._menu_action.addAction(self._action_destroy_trash)
        self._menu_action.addSeparator()
        self._menu_action.addAction(self._action_delete)
        self._menubar.addAction(self._menu_program.menuAction())
        self._menubar.addAction(self._menu_view.menuAction())
        self._menubar.addAction(self._menu_action.menuAction())
        self._menubar.addAction(self._menu_help.menuAction())
        self._toolbar.addAction(self._action_lock)
        self._toolbar.addAction(self._action_unlock)
        self._toolbar.addSeparator()
        self._toolbar.addAction(self._action_destroy_clipboard)
        self._toolbar.addAction(self._action_destroy_trash)
        self._toolbar.addSeparator()
        self._toolbar.addAction(self._action_delete)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self._action_quit, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "BUMM 1.0 - BSCW Userverwaltung", None, QtGui.QApplication.UnicodeUTF8))
        self._menu_program.setTitle(QtGui.QApplication.translate("MainWindow", "Programm", None, QtGui.QApplication.UnicodeUTF8))
        self._menu_view.setTitle(QtGui.QApplication.translate("MainWindow", "Ansicht", None, QtGui.QApplication.UnicodeUTF8))
        self._menu_help.setTitle(QtGui.QApplication.translate("MainWindow", "Hilfe", None, QtGui.QApplication.UnicodeUTF8))
        self._menu_action.setTitle(QtGui.QApplication.translate("MainWindow", "Aktion", None, QtGui.QApplication.UnicodeUTF8))
        self._toolbar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self._action_quit.setText(QtGui.QApplication.translate("MainWindow", "Beenden", None, QtGui.QApplication.UnicodeUTF8))
        self._action_info.setText(QtGui.QApplication.translate("MainWindow", "Über", None, QtGui.QApplication.UnicodeUTF8))
        self._action_user_Details.setText(QtGui.QApplication.translate("MainWindow", "User Details", None, QtGui.QApplication.UnicodeUTF8))
        self._action_set_cols.setText(QtGui.QApplication.translate("MainWindow", "Spalten auswählen", None, QtGui.QApplication.UnicodeUTF8))
        self._action_delete.setText(QtGui.QApplication.translate("MainWindow", "Benutzer löschen", None, QtGui.QApplication.UnicodeUTF8))
        self._action_destroy_clipboard.setText(QtGui.QApplication.translate("MainWindow", "Ablage(n) aufräumen", None, QtGui.QApplication.UnicodeUTF8))
        self._action_destroy_trash.setText(QtGui.QApplication.translate("MainWindow", "Mülleimer leeren", None, QtGui.QApplication.UnicodeUTF8))
        self._action_lock.setText(QtGui.QApplication.translate("MainWindow", "Benutzer sperren", None, QtGui.QApplication.UnicodeUTF8))
        self._action_unlock.setText(QtGui.QApplication.translate("MainWindow", "Benutzer entsperren", None, QtGui.QApplication.UnicodeUTF8))

import images_rc
