# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SetColoumnDialog.ui'
#
# Created: Thu Feb 12 14:30:36 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_SetColoumnDialog(object):
    def setupUi(self, SetColoumnDialog):
        SetColoumnDialog.setObjectName("SetColoumnDialog")
        SetColoumnDialog.resize(400, 336)
        self.buttonBox = QtGui.QDialogButtonBox(SetColoumnDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 290, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self._chkbox_user_id = QtGui.QCheckBox(SetColoumnDialog)
        self._chkbox_user_id.setGeometry(QtCore.QRect(20, 20, 72, 18))
        self._chkbox_user_id.setObjectName("_chkbox_user_id")
        self._chkbox_name = QtGui.QCheckBox(SetColoumnDialog)
        self._chkbox_name.setGeometry(QtCore.QRect(20, 40, 91, 18))
        self._chkbox_name.setObjectName("_chkbox_name")
        self._chkbox_longname = QtGui.QCheckBox(SetColoumnDialog)
        self._chkbox_longname.setGeometry(QtCore.QRect(20, 60, 121, 18))
        self._chkbox_longname.setObjectName("_chkbox_longname")
        self._chkbox_email = QtGui.QCheckBox(SetColoumnDialog)
        self._chkbox_email.setGeometry(QtCore.QRect(20, 80, 91, 18))
        self._chkbox_email.setObjectName("_chkbox_email")
        self._chkbox_secondary_mail = QtGui.QCheckBox(SetColoumnDialog)
        self._chkbox_secondary_mail.setGeometry(QtCore.QRect(20, 100, 141, 18))
        self._chkbox_secondary_mail.setObjectName("_chkbox_secondary_mail")
        self._chkbox_organization = QtGui.QCheckBox(SetColoumnDialog)
        self._chkbox_organization.setGeometry(QtCore.QRect(20, 120, 91, 18))
        self._chkbox_organization.setObjectName("_chkbox_organization")
        self._chkbox_phone_home = QtGui.QCheckBox(SetColoumnDialog)
        self._chkbox_phone_home.setGeometry(QtCore.QRect(20, 140, 91, 18))
        self._chkbox_phone_home.setObjectName("_chkbox_phone_home")
        self._chkbox_phone_mobile = QtGui.QCheckBox(SetColoumnDialog)
        self._chkbox_phone_mobile.setGeometry(QtCore.QRect(20, 160, 91, 18))
        self._chkbox_phone_mobile.setObjectName("_chkbox_phone_mobile")
        self._chkbox_phone_office = QtGui.QCheckBox(SetColoumnDialog)
        self._chkbox_phone_office.setGeometry(QtCore.QRect(20, 180, 121, 18))
        self._chkbox_phone_office.setObjectName("_chkbox_phone_office")
        self._chkbox_fax = QtGui.QCheckBox(SetColoumnDialog)
        self._chkbox_fax.setGeometry(QtCore.QRect(20, 200, 41, 18))
        self._chkbox_fax.setObjectName("_chkbox_fax")
        self._chkbox_language = QtGui.QCheckBox(SetColoumnDialog)
        self._chkbox_language.setGeometry(QtCore.QRect(20, 220, 72, 18))
        self._chkbox_language.setObjectName("_chkbox_language")
        self._chkbox_address = QtGui.QCheckBox(SetColoumnDialog)
        self._chkbox_address.setGeometry(QtCore.QRect(20, 240, 72, 18))
        self._chkbox_address.setObjectName("_chkbox_address")
        self._chkbox_url_homepage = QtGui.QCheckBox(SetColoumnDialog)
        self._chkbox_url_homepage.setGeometry(QtCore.QRect(220, 60, 91, 18))
        self._chkbox_url_homepage.setObjectName("_chkbox_url_homepage")
        self._chkbox_url = QtGui.QCheckBox(SetColoumnDialog)
        self._chkbox_url.setGeometry(QtCore.QRect(220, 40, 121, 18))
        self._chkbox_url.setObjectName("_chkbox_url")
        self._chkbox_messaging_services = QtGui.QCheckBox(SetColoumnDialog)
        self._chkbox_messaging_services.setGeometry(QtCore.QRect(220, 20, 121, 18))
        self._chkbox_messaging_services.setObjectName("_chkbox_messaging_services")
        self._chkbox_additional_info = QtGui.QCheckBox(SetColoumnDialog)
        self._chkbox_additional_info.setGeometry(QtCore.QRect(20, 260, 151, 18))
        self._chkbox_additional_info.setObjectName("_chkbox_additional_info")
        self._chkbox_photo = QtGui.QCheckBox(SetColoumnDialog)
        self._chkbox_photo.setGeometry(QtCore.QRect(220, 80, 72, 18))
        self._chkbox_photo.setObjectName("_chkbox_photo")
        self._chkbox_locked = QtGui.QCheckBox(SetColoumnDialog)
        self._chkbox_locked.setGeometry(QtCore.QRect(220, 100, 72, 18))
        self._chkbox_locked.setObjectName("_chkbox_locked")
        self._chkbox_used_memory = QtGui.QCheckBox(SetColoumnDialog)
        self._chkbox_used_memory.setGeometry(QtCore.QRect(220, 120, 111, 18))
        self._chkbox_used_memory.setObjectName("_chkbox_used_memory")
        self._chkbox_last_login = QtGui.QCheckBox(SetColoumnDialog)
        self._chkbox_last_login.setGeometry(QtCore.QRect(220, 140, 91, 18))
        self._chkbox_last_login.setObjectName("_chkbox_last_login")
        self._chkbox_create_time = QtGui.QCheckBox(SetColoumnDialog)
        self._chkbox_create_time.setGeometry(QtCore.QRect(220, 160, 81, 18))
        self._chkbox_create_time.setObjectName("_chkbox_create_time")
        self._chkbox_files = QtGui.QCheckBox(SetColoumnDialog)
        self._chkbox_files.setGeometry(QtCore.QRect(220, 180, 111, 18))
        self._chkbox_files.setObjectName("_chkbox_files")
        self._chkbox_admin = QtGui.QCheckBox(SetColoumnDialog)
        self._chkbox_admin.setGeometry(QtCore.QRect(220, 200, 131, 18))
        self._chkbox_admin.setObjectName("_chkbox_admin")
        self._chkbox_workspaces = QtGui.QCheckBox(SetColoumnDialog)
        self._chkbox_workspaces.setGeometry(QtCore.QRect(220, 220, 101, 18))
        self._chkbox_workspaces.setObjectName("_chkbox_workspaces")
        self._chkbox_access_right = QtGui.QCheckBox(SetColoumnDialog)
        self._chkbox_access_right.setGeometry(QtCore.QRect(220, 240, 161, 18))
        self._chkbox_access_right.setObjectName("_chkbox_access_right")

        self.retranslateUi(SetColoumnDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), SetColoumnDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), SetColoumnDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SetColoumnDialog)

    def retranslateUi(self, SetColoumnDialog):
        SetColoumnDialog.setWindowTitle(QtGui.QApplication.translate("SetColoumnDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self._chkbox_user_id.setText(QtGui.QApplication.translate("SetColoumnDialog", "UserID", None, QtGui.QApplication.UnicodeUTF8))
        self._chkbox_name.setText(QtGui.QApplication.translate("SetColoumnDialog", "Benutzername", None, QtGui.QApplication.UnicodeUTF8))
        self._chkbox_longname.setText(QtGui.QApplication.translate("SetColoumnDialog", "Vor- und Nachname", None, QtGui.QApplication.UnicodeUTF8))
        self._chkbox_email.setText(QtGui.QApplication.translate("SetColoumnDialog", "Email-Adresse", None, QtGui.QApplication.UnicodeUTF8))
        self._chkbox_secondary_mail.setText(QtGui.QApplication.translate("SetColoumnDialog", "Weitere Email-Adressen", None, QtGui.QApplication.UnicodeUTF8))
        self._chkbox_organization.setText(QtGui.QApplication.translate("SetColoumnDialog", "Organisation", None, QtGui.QApplication.UnicodeUTF8))
        self._chkbox_phone_home.setText(QtGui.QApplication.translate("SetColoumnDialog", "Telefon privat", None, QtGui.QApplication.UnicodeUTF8))
        self._chkbox_phone_mobile.setText(QtGui.QApplication.translate("SetColoumnDialog", "Telefon mobil", None, QtGui.QApplication.UnicodeUTF8))
        self._chkbox_phone_office.setText(QtGui.QApplication.translate("SetColoumnDialog", "Telefon geschäftlich", None, QtGui.QApplication.UnicodeUTF8))
        self._chkbox_fax.setText(QtGui.QApplication.translate("SetColoumnDialog", "Fax", None, QtGui.QApplication.UnicodeUTF8))
        self._chkbox_language.setText(QtGui.QApplication.translate("SetColoumnDialog", "Sprache", None, QtGui.QApplication.UnicodeUTF8))
        self._chkbox_address.setText(QtGui.QApplication.translate("SetColoumnDialog", "Addresse", None, QtGui.QApplication.UnicodeUTF8))
        self._chkbox_url_homepage.setText(QtGui.QApplication.translate("SetColoumnDialog", "Website privat", None, QtGui.QApplication.UnicodeUTF8))
        self._chkbox_url.setText(QtGui.QApplication.translate("SetColoumnDialog", "Website geschäftlich", None, QtGui.QApplication.UnicodeUTF8))
        self._chkbox_messaging_services.setText(QtGui.QApplication.translate("SetColoumnDialog", "Messaging Services", None, QtGui.QApplication.UnicodeUTF8))
        self._chkbox_additional_info.setText(QtGui.QApplication.translate("SetColoumnDialog", "Zusätzliche Informationen", None, QtGui.QApplication.UnicodeUTF8))
        self._chkbox_photo.setText(QtGui.QApplication.translate("SetColoumnDialog", "Foto", None, QtGui.QApplication.UnicodeUTF8))
        self._chkbox_locked.setText(QtGui.QApplication.translate("SetColoumnDialog", "Sperrung", None, QtGui.QApplication.UnicodeUTF8))
        self._chkbox_used_memory.setText(QtGui.QApplication.translate("SetColoumnDialog", "Speicherverbrauch", None, QtGui.QApplication.UnicodeUTF8))
        self._chkbox_last_login.setText(QtGui.QApplication.translate("SetColoumnDialog", "Letzter Login", None, QtGui.QApplication.UnicodeUTF8))
        self._chkbox_create_time.setText(QtGui.QApplication.translate("SetColoumnDialog", "Mitglied seit", None, QtGui.QApplication.UnicodeUTF8))
        self._chkbox_files.setText(QtGui.QApplication.translate("SetColoumnDialog", "Anzahl der Dateien", None, QtGui.QApplication.UnicodeUTF8))
        self._chkbox_admin.setText(QtGui.QApplication.translate("SetColoumnDialog", "Administratorenrechte", None, QtGui.QApplication.UnicodeUTF8))
        self._chkbox_workspaces.setText(QtGui.QApplication.translate("SetColoumnDialog", "Arbeitsbereiche", None, QtGui.QApplication.UnicodeUTF8))
        self._chkbox_access_right.setText(QtGui.QApplication.translate("SetColoumnDialog", "Zugriffsrechte des Benutzers", None, QtGui.QApplication.UnicodeUTF8))

