# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UserDetails.ui'
#
# Created: Fri Feb 27 10:59:35 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_UserDetails(object):
    def setupUi(self, UserDetails):
        UserDetails.setObjectName("UserDetails")
        UserDetails.resize(372, 439)
        UserDetails.setMinimumSize(QtCore.QSize(372, 439))
        self._content = QtGui.QWidget()
        self._content.setObjectName("_content")
        self.gridLayout = QtGui.QGridLayout(self._content)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self._lbl_user = QtGui.QLabel(self._content)
        self._lbl_user.setMinimumSize(QtCore.QSize(41, 16))
        self._lbl_user.setMaximumSize(QtCore.QSize(41, 16))
        self._lbl_user.setObjectName("_lbl_user")
        self.horizontalLayout.addWidget(self._lbl_user)
        self._user = QtGui.QLineEdit(self._content)
        self._user.setEnabled(True)
        self._user.setMinimumSize(QtCore.QSize(107, 20))
        self._user.setFrame(True)
        self._user.setReadOnly(True)
        self._user.setObjectName("_user")
        self.horizontalLayout.addWidget(self._user)
        self._lbl_user_id = QtGui.QLabel(self._content)
        self._lbl_user_id.setMinimumSize(QtCore.QSize(57, 16))
        self._lbl_user_id.setMaximumSize(QtCore.QSize(57, 16))
        self._lbl_user_id.setObjectName("_lbl_user_id")
        self.horizontalLayout.addWidget(self._lbl_user_id)
        self._user_id = QtGui.QLineEdit(self._content)
        self._user_id.setMinimumSize(QtCore.QSize(85, 20))
        self._user_id.setReadOnly(True)
        self._user_id.setObjectName("_user_id")
        self.horizontalLayout.addWidget(self._user_id)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self._user_info_tabs = QtGui.QTabWidget(self._content)
        self._user_info_tabs.setMinimumSize(QtCore.QSize(339, 371))
        self._user_info_tabs.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self._user_info_tabs.setObjectName("_user_info_tabs")
        self._info_tab = QtGui.QWidget()
        self._info_tab.setObjectName("_info_tab")
        self.gridLayout_2 = QtGui.QGridLayout(self._info_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self._lbl_full_name = QtGui.QLabel(self._info_tab)
        self._lbl_full_name.setMinimumSize(QtCore.QSize(125, 16))
        self._lbl_full_name.setMaximumSize(QtCore.QSize(125, 16))
        self._lbl_full_name.setObjectName("_lbl_full_name")
        self.gridLayout_2.addWidget(self._lbl_full_name, 0, 0, 1, 1)
        self._full_name = QtGui.QLineEdit(self._info_tab)
        self._full_name.setMinimumSize(QtCore.QSize(190, 20))
        self._full_name.setReadOnly(True)
        self._full_name.setObjectName("_full_name")
        self.gridLayout_2.addWidget(self._full_name, 0, 1, 1, 1)
        self._lbl_admin = QtGui.QLabel(self._info_tab)
        self._lbl_admin.setMinimumSize(QtCore.QSize(125, 16))
        self._lbl_admin.setMaximumSize(QtCore.QSize(125, 16))
        self._lbl_admin.setObjectName("_lbl_admin")
        self.gridLayout_2.addWidget(self._lbl_admin, 1, 0, 1, 1)
        self._admin = QtGui.QLineEdit(self._info_tab)
        self._admin.setMinimumSize(QtCore.QSize(190, 20))
        self._admin.setReadOnly(True)
        self._admin.setObjectName("_admin")
        self.gridLayout_2.addWidget(self._admin, 1, 1, 1, 1)
        self._lbl_locked = QtGui.QLabel(self._info_tab)
        self._lbl_locked.setMinimumSize(QtCore.QSize(125, 16))
        self._lbl_locked.setMaximumSize(QtCore.QSize(125, 16))
        self._lbl_locked.setObjectName("_lbl_locked")
        self.gridLayout_2.addWidget(self._lbl_locked, 2, 0, 1, 1)
        self._locked = QtGui.QLineEdit(self._info_tab)
        self._locked.setMinimumSize(QtCore.QSize(190, 20))
        self._locked.setReadOnly(True)
        self._locked.setObjectName("_locked")
        self.gridLayout_2.addWidget(self._locked, 2, 1, 1, 1)
        self._lbl_mail = QtGui.QLabel(self._info_tab)
        self._lbl_mail.setMinimumSize(QtCore.QSize(125, 16))
        self._lbl_mail.setMaximumSize(QtCore.QSize(125, 16))
        self._lbl_mail.setObjectName("_lbl_mail")
        self.gridLayout_2.addWidget(self._lbl_mail, 3, 0, 1, 1)
        self._mail = QtGui.QLineEdit(self._info_tab)
        self._mail.setMinimumSize(QtCore.QSize(190, 20))
        self._mail.setReadOnly(True)
        self._mail.setObjectName("_mail")
        self.gridLayout_2.addWidget(self._mail, 3, 1, 1, 1)
        self._lbl_more_mail = QtGui.QLabel(self._info_tab)
        self._lbl_more_mail.setMinimumSize(QtCore.QSize(125, 40))
        self._lbl_more_mail.setMaximumSize(QtCore.QSize(125, 40))
        self._lbl_more_mail.setObjectName("_lbl_more_mail")
        self.gridLayout_2.addWidget(self._lbl_more_mail, 4, 0, 1, 1)
        self._more_mail = QtGui.QTextEdit(self._info_tab)
        self._more_mail.setMinimumSize(QtCore.QSize(190, 40))
        self._more_mail.setReadOnly(True)
        self._more_mail.setObjectName("_more_mail")
        self.gridLayout_2.addWidget(self._more_mail, 4, 1, 1, 1)
        self._lbl_last_login = QtGui.QLabel(self._info_tab)
        self._lbl_last_login.setMinimumSize(QtCore.QSize(125, 16))
        self._lbl_last_login.setMaximumSize(QtCore.QSize(125, 16))
        self._lbl_last_login.setObjectName("_lbl_last_login")
        self.gridLayout_2.addWidget(self._lbl_last_login, 5, 0, 1, 1)
        self._last_login = QtGui.QLineEdit(self._info_tab)
        self._last_login.setMinimumSize(QtCore.QSize(190, 20))
        self._last_login.setFrame(True)
        self._last_login.setReadOnly(True)
        self._last_login.setObjectName("_last_login")
        self.gridLayout_2.addWidget(self._last_login, 5, 1, 1, 1)
        self._lbl_workspace = QtGui.QLabel(self._info_tab)
        self._lbl_workspace.setMinimumSize(QtCore.QSize(125, 45))
        self._lbl_workspace.setMaximumSize(QtCore.QSize(125, 45))
        self._lbl_workspace.setObjectName("_lbl_workspace")
        self.gridLayout_2.addWidget(self._lbl_workspace, 6, 0, 1, 1)
        self._workspace = QtGui.QTextEdit(self._info_tab)
        self._workspace.setMinimumSize(QtCore.QSize(190, 45))
        self._workspace.setReadOnly(True)
        self._workspace.setObjectName("_workspace")
        self.gridLayout_2.addWidget(self._workspace, 6, 1, 1, 1)
        self._user_info_tabs.addTab(self._info_tab, "")
        self._account_tab = QtGui.QWidget()
        self._account_tab.setObjectName("_account_tab")
        self.gridLayout_5 = QtGui.QGridLayout(self._account_tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self._lbl_create_time = QtGui.QLabel(self._account_tab)
        self._lbl_create_time.setMinimumSize(QtCore.QSize(125, 16))
        self._lbl_create_time.setMaximumSize(QtCore.QSize(125, 16))
        self._lbl_create_time.setObjectName("_lbl_create_time")
        self.gridLayout_5.addWidget(self._lbl_create_time, 0, 0, 1, 1)
        self._create_time = QtGui.QLineEdit(self._account_tab)
        self._create_time.setMinimumSize(QtCore.QSize(190, 20))
        self._create_time.setReadOnly(True)
        self._create_time.setObjectName("_create_time")
        self.gridLayout_5.addWidget(self._create_time, 0, 1, 1, 1)
        self._lbl_storage_usage = QtGui.QLabel(self._account_tab)
        self._lbl_storage_usage.setMinimumSize(QtCore.QSize(125, 16))
        self._lbl_storage_usage.setMaximumSize(QtCore.QSize(125, 16))
        self._lbl_storage_usage.setObjectName("_lbl_storage_usage")
        self.gridLayout_5.addWidget(self._lbl_storage_usage, 1, 0, 1, 1)
        self._storage_usage = QtGui.QLineEdit(self._account_tab)
        self._storage_usage.setMinimumSize(QtCore.QSize(190, 20))
        self._storage_usage.setReadOnly(True)
        self._storage_usage.setObjectName("_storage_usage")
        self.gridLayout_5.addWidget(self._storage_usage, 1, 1, 1, 1)
        self._lbl_objects = QtGui.QLabel(self._account_tab)
        self._lbl_objects.setMinimumSize(QtCore.QSize(125, 16))
        self._lbl_objects.setMaximumSize(QtCore.QSize(125, 16))
        self._lbl_objects.setObjectName("_lbl_objects")
        self.gridLayout_5.addWidget(self._lbl_objects, 2, 0, 1, 1)
        self._objects = QtGui.QLineEdit(self._account_tab)
        self._objects.setMinimumSize(QtCore.QSize(190, 20))
        self._objects.setReadOnly(True)
        self._objects.setObjectName("_objects")
        self.gridLayout_5.addWidget(self._objects, 2, 1, 1, 1)
        self._access_rights_box = QtGui.QGroupBox(self._account_tab)
        self._access_rights_box.setMinimumSize(QtCore.QSize(325, 160))
        self._access_rights_box.setObjectName("_access_rights_box")
        self.gridLayout_6 = QtGui.QGridLayout(self._access_rights_box)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self._grid_layout_account = QtGui.QGridLayout()
        self._grid_layout_account.setSpacing(5)
        self._grid_layout_account.setObjectName("_grid_layout_account")
        self._lbl_role = QtGui.QLabel(self._access_rights_box)
        self._lbl_role.setMinimumSize(QtCore.QSize(55, 16))
        self._lbl_role.setObjectName("_lbl_role")
        self._grid_layout_account.addWidget(self._lbl_role, 0, 0, 1, 1)
        self._lbl_role_owner = QtGui.QLabel(self._access_rights_box)
        self._lbl_role_owner.setMinimumSize(QtCore.QSize(121, 16))
        self._lbl_role_owner.setObjectName("_lbl_role_owner")
        self._grid_layout_account.addWidget(self._lbl_role_owner, 0, 1, 1, 1)
        self._lbl_authorized_actions = QtGui.QLabel(self._access_rights_box)
        self._lbl_authorized_actions.setMinimumSize(QtCore.QSize(121, 16))
        self._lbl_authorized_actions.setObjectName("_lbl_authorized_actions")
        self._grid_layout_account.addWidget(self._lbl_authorized_actions, 0, 2, 1, 1)
        self._lbl_owner = QtGui.QLabel(self._access_rights_box)
        self._lbl_owner.setMinimumSize(QtCore.QSize(55, 35))
        self._lbl_owner.setMaximumSize(QtCore.QSize(55, 35))
        self._lbl_owner.setObjectName("_lbl_owner")
        self._grid_layout_account.addWidget(self._lbl_owner, 1, 0, 1, 1)
        self._role_owner_as_owner = QtGui.QTextEdit(self._access_rights_box)
        self._role_owner_as_owner.setMinimumSize(QtCore.QSize(121, 35))
        self._role_owner_as_owner.setReadOnly(True)
        self._role_owner_as_owner.setObjectName("_role_owner_as_owner")
        self._grid_layout_account.addWidget(self._role_owner_as_owner, 1, 1, 1, 1)
        self._actions_as_owner = QtGui.QTextEdit(self._access_rights_box)
        self._actions_as_owner.setMinimumSize(QtCore.QSize(121, 35))
        self._actions_as_owner.setReadOnly(True)
        self._actions_as_owner.setObjectName("_actions_as_owner")
        self._grid_layout_account.addWidget(self._actions_as_owner, 1, 2, 1, 1)
        self._lbl_manager = QtGui.QLabel(self._access_rights_box)
        self._lbl_manager.setMinimumSize(QtCore.QSize(55, 35))
        self._lbl_manager.setMaximumSize(QtCore.QSize(55, 35))
        self._lbl_manager.setObjectName("_lbl_manager")
        self._grid_layout_account.addWidget(self._lbl_manager, 2, 0, 1, 1)
        self._role_owner_as_manager = QtGui.QTextEdit(self._access_rights_box)
        self._role_owner_as_manager.setMinimumSize(QtCore.QSize(121, 35))
        self._role_owner_as_manager.setReadOnly(True)
        self._role_owner_as_manager.setObjectName("_role_owner_as_manager")
        self._grid_layout_account.addWidget(self._role_owner_as_manager, 2, 1, 1, 1)
        self._actions_as_manager = QtGui.QTextEdit(self._access_rights_box)
        self._actions_as_manager.setMinimumSize(QtCore.QSize(121, 35))
        self._actions_as_manager.setReadOnly(True)
        self._actions_as_manager.setObjectName("_actions_as_manager")
        self._grid_layout_account.addWidget(self._actions_as_manager, 2, 2, 1, 1)
        self._lbl_other = QtGui.QLabel(self._access_rights_box)
        self._lbl_other.setMinimumSize(QtCore.QSize(55, 35))
        self._lbl_other.setMaximumSize(QtCore.QSize(55, 35))
        self._lbl_other.setObjectName("_lbl_other")
        self._grid_layout_account.addWidget(self._lbl_other, 3, 0, 1, 1)
        self._role_owner_as_other = QtGui.QTextEdit(self._access_rights_box)
        self._role_owner_as_other.setMinimumSize(QtCore.QSize(121, 35))
        self._role_owner_as_other.setReadOnly(True)
        self._role_owner_as_other.setObjectName("_role_owner_as_other")
        self._grid_layout_account.addWidget(self._role_owner_as_other, 3, 1, 1, 1)
        self._actions_as_other = QtGui.QTextEdit(self._access_rights_box)
        self._actions_as_other.setMinimumSize(QtCore.QSize(121, 35))
        self._actions_as_other.setReadOnly(True)
        self._actions_as_other.setObjectName("_actions_as_other")
        self._grid_layout_account.addWidget(self._actions_as_other, 3, 2, 1, 1)
        self.gridLayout_6.addLayout(self._grid_layout_account, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self._access_rights_box, 3, 0, 1, 2)
        self._user_info_tabs.addTab(self._account_tab, "")
        self._personal_tab = QtGui.QWidget()
        self._personal_tab.setObjectName("_personal_tab")
        self.gridLayout_4 = QtGui.QGridLayout(self._personal_tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self._phone_box = QtGui.QGroupBox(self._personal_tab)
        self._phone_box.setMinimumSize(QtCore.QSize(325, 120))
        self._phone_box.setObjectName("_phone_box")
        self.gridLayout_3 = QtGui.QGridLayout(self._phone_box)
        self.gridLayout_3.setVerticalSpacing(5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self._lbl_private_tel = QtGui.QLabel(self._phone_box)
        self._lbl_private_tel.setMinimumSize(QtCore.QSize(122, 16))
        self._lbl_private_tel.setMaximumSize(QtCore.QSize(122, 16))
        self._lbl_private_tel.setObjectName("_lbl_private_tel")
        self.gridLayout_3.addWidget(self._lbl_private_tel, 0, 0, 1, 1)
        self._lbl_mobile_tel = QtGui.QLabel(self._phone_box)
        self._lbl_mobile_tel.setMinimumSize(QtCore.QSize(122, 16))
        self._lbl_mobile_tel.setMaximumSize(QtCore.QSize(122, 16))
        self._lbl_mobile_tel.setObjectName("_lbl_mobile_tel")
        self.gridLayout_3.addWidget(self._lbl_mobile_tel, 1, 0, 1, 1)
        self._mobile_tel = QtGui.QLineEdit(self._phone_box)
        self._mobile_tel.setMinimumSize(QtCore.QSize(187, 20))
        self._mobile_tel.setReadOnly(True)
        self._mobile_tel.setObjectName("_mobile_tel")
        self.gridLayout_3.addWidget(self._mobile_tel, 1, 1, 1, 1)
        self._lbl_office_tel = QtGui.QLabel(self._phone_box)
        self._lbl_office_tel.setMinimumSize(QtCore.QSize(122, 16))
        self._lbl_office_tel.setMaximumSize(QtCore.QSize(122, 16))
        self._lbl_office_tel.setObjectName("_lbl_office_tel")
        self.gridLayout_3.addWidget(self._lbl_office_tel, 2, 0, 1, 1)
        self._office_tel = QtGui.QLineEdit(self._phone_box)
        self._office_tel.setMinimumSize(QtCore.QSize(187, 20))
        self._office_tel.setReadOnly(True)
        self._office_tel.setObjectName("_office_tel")
        self.gridLayout_3.addWidget(self._office_tel, 2, 1, 1, 1)
        self._lbl_fax = QtGui.QLabel(self._phone_box)
        self._lbl_fax.setMinimumSize(QtCore.QSize(122, 16))
        self._lbl_fax.setMaximumSize(QtCore.QSize(122, 16))
        self._lbl_fax.setObjectName("_lbl_fax")
        self.gridLayout_3.addWidget(self._lbl_fax, 3, 0, 1, 1)
        self._fax = QtGui.QLineEdit(self._phone_box)
        self._fax.setMinimumSize(QtCore.QSize(187, 20))
        self._fax.setReadOnly(True)
        self._fax.setObjectName("_fax")
        self.gridLayout_3.addWidget(self._fax, 3, 1, 1, 1)
        self._private_tel = QtGui.QLineEdit(self._phone_box)
        self._private_tel.setMinimumSize(QtCore.QSize(187, 20))
        self._private_tel.setReadOnly(True)
        self._private_tel.setObjectName("_private_tel")
        self.gridLayout_3.addWidget(self._private_tel, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self._phone_box, 0, 0, 1, 1)
        self._personal_form = QtGui.QFormLayout()
        self._personal_form.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self._personal_form.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self._personal_form.setContentsMargins(-1, 0, -1, -1)
        self._personal_form.setHorizontalSpacing(0)
        self._personal_form.setVerticalSpacing(5)
        self._personal_form.setObjectName("_personal_form")
        self._lbl_language = QtGui.QLabel(self._personal_tab)
        self._lbl_language.setMinimumSize(QtCore.QSize(135, 16))
        self._lbl_language.setMaximumSize(QtCore.QSize(125, 16))
        self._lbl_language.setObjectName("_lbl_language")
        self._personal_form.setWidget(0, QtGui.QFormLayout.LabelRole, self._lbl_language)
        self._language = QtGui.QLineEdit(self._personal_tab)
        self._language.setMinimumSize(QtCore.QSize(190, 20))
        self._language.setReadOnly(True)
        self._language.setObjectName("_language")
        self._personal_form.setWidget(0, QtGui.QFormLayout.FieldRole, self._language)
        self._lbl_organisation = QtGui.QLabel(self._personal_tab)
        self._lbl_organisation.setMinimumSize(QtCore.QSize(135, 16))
        self._lbl_organisation.setMaximumSize(QtCore.QSize(125, 16))
        self._lbl_organisation.setObjectName("_lbl_organisation")
        self._personal_form.setWidget(1, QtGui.QFormLayout.LabelRole, self._lbl_organisation)
        self._organisation = QtGui.QLineEdit(self._personal_tab)
        self._organisation.setMinimumSize(QtCore.QSize(190, 20))
        self._organisation.setReadOnly(True)
        self._organisation.setObjectName("_organisation")
        self._personal_form.setWidget(1, QtGui.QFormLayout.FieldRole, self._organisation)
        self._lbl_office_url = QtGui.QLabel(self._personal_tab)
        self._lbl_office_url.setMinimumSize(QtCore.QSize(135, 16))
        self._lbl_office_url.setMaximumSize(QtCore.QSize(125, 16))
        self._lbl_office_url.setObjectName("_lbl_office_url")
        self._personal_form.setWidget(2, QtGui.QFormLayout.LabelRole, self._lbl_office_url)
        self._office_url = QtGui.QLineEdit(self._personal_tab)
        self._office_url.setMinimumSize(QtCore.QSize(190, 20))
        self._office_url.setReadOnly(True)
        self._office_url.setObjectName("_office_url")
        self._personal_form.setWidget(2, QtGui.QFormLayout.FieldRole, self._office_url)
        self._lbl_private_url = QtGui.QLabel(self._personal_tab)
        self._lbl_private_url.setMinimumSize(QtCore.QSize(135, 16))
        self._lbl_private_url.setMaximumSize(QtCore.QSize(125, 16))
        self._lbl_private_url.setObjectName("_lbl_private_url")
        self._personal_form.setWidget(3, QtGui.QFormLayout.LabelRole, self._lbl_private_url)
        self._private_url = QtGui.QLineEdit(self._personal_tab)
        self._private_url.setMinimumSize(QtCore.QSize(190, 20))
        self._private_url.setReadOnly(True)
        self._private_url.setObjectName("_private_url")
        self._personal_form.setWidget(3, QtGui.QFormLayout.FieldRole, self._private_url)
        self._lbl_address = QtGui.QLabel(self._personal_tab)
        self._lbl_address.setMinimumSize(QtCore.QSize(135, 45))
        self._lbl_address.setMaximumSize(QtCore.QSize(125, 45))
        self._lbl_address.setObjectName("_lbl_address")
        self._personal_form.setWidget(4, QtGui.QFormLayout.LabelRole, self._lbl_address)
        self._address = QtGui.QTextEdit(self._personal_tab)
        self._address.setReadOnly(True)
        self._address.setObjectName("_address")
        self._personal_form.setWidget(4, QtGui.QFormLayout.FieldRole, self._address)
        self._lbl_instant_messenger = QtGui.QLabel(self._personal_tab)
        self._lbl_instant_messenger.setMinimumSize(QtCore.QSize(135, 45))
        self._lbl_instant_messenger.setMaximumSize(QtCore.QSize(125, 45))
        self._lbl_instant_messenger.setObjectName("_lbl_instant_messenger")
        self._personal_form.setWidget(5, QtGui.QFormLayout.LabelRole, self._lbl_instant_messenger)
        self._instant_messenger = QtGui.QTextEdit(self._personal_tab)
        self._instant_messenger.setReadOnly(True)
        self._instant_messenger.setObjectName("_instant_messenger")
        self._personal_form.setWidget(5, QtGui.QFormLayout.FieldRole, self._instant_messenger)
        self._lbl_more_info = QtGui.QLabel(self._personal_tab)
        self._lbl_more_info.setMinimumSize(QtCore.QSize(135, 45))
        self._lbl_more_info.setMaximumSize(QtCore.QSize(125, 45))
        self._lbl_more_info.setObjectName("_lbl_more_info")
        self._personal_form.setWidget(6, QtGui.QFormLayout.LabelRole, self._lbl_more_info)
        self._more_info = QtGui.QTextEdit(self._personal_tab)
        self._more_info.setReadOnly(True)
        self._more_info.setObjectName("_more_info")
        self._personal_form.setWidget(6, QtGui.QFormLayout.FieldRole, self._more_info)
        self.gridLayout_4.addLayout(self._personal_form, 1, 0, 1, 1)
        self._user_info_tabs.addTab(self._personal_tab, "")
        self._pic_tab = QtGui.QWidget()
        self._pic_tab.setObjectName("_pic_tab")
        self._lbl_pic = QtGui.QLabel(self._pic_tab)
        self._lbl_pic.setGeometry(QtCore.QRect(5, 5, 321, 331))
        self._lbl_pic.setObjectName("_lbl_pic")
        self._user_info_tabs.addTab(self._pic_tab, "")
        self.gridLayout.addWidget(self._user_info_tabs, 1, 0, 1, 1)
        UserDetails.setWidget(self._content)

        self.retranslateUi(UserDetails)
        self._user_info_tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(UserDetails)

    def retranslateUi(self, UserDetails):
        UserDetails.setWindowTitle(QtGui.QApplication.translate("UserDetails", "Details", None, QtGui.QApplication.UnicodeUTF8))
        self._lbl_user.setText(QtGui.QApplication.translate("UserDetails", "Benutzer", None, QtGui.QApplication.UnicodeUTF8))
        self._lbl_user_id.setText(QtGui.QApplication.translate("UserDetails", "Benutzer-ID", None, QtGui.QApplication.UnicodeUTF8))
        self._lbl_full_name.setText(QtGui.QApplication.translate("UserDetails", "Vollständiger Name", None, QtGui.QApplication.UnicodeUTF8))
        self._lbl_admin.setText(QtGui.QApplication.translate("UserDetails", "Administrator", None, QtGui.QApplication.UnicodeUTF8))
        self._lbl_locked.setText(QtGui.QApplication.translate("UserDetails", "Gesperrt", None, QtGui.QApplication.UnicodeUTF8))
        self._lbl_mail.setText(QtGui.QApplication.translate("UserDetails", "Primäre E-Mail Adresse", None, QtGui.QApplication.UnicodeUTF8))
        self._lbl_more_mail.setText(QtGui.QApplication.translate("UserDetails", "weitere E-Mail Adressen", None, QtGui.QApplication.UnicodeUTF8))
        self._lbl_last_login.setText(QtGui.QApplication.translate("UserDetails", "Letzte Anmeldung", None, QtGui.QApplication.UnicodeUTF8))
        self._lbl_workspace.setText(QtGui.QApplication.translate("UserDetails", "Arbeitsbereiche", None, QtGui.QApplication.UnicodeUTF8))
        self._user_info_tabs.setTabText(self._user_info_tabs.indexOf(self._info_tab), QtGui.QApplication.translate("UserDetails", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self._lbl_create_time.setText(QtGui.QApplication.translate("UserDetails", "Erstellungsdatum", None, QtGui.QApplication.UnicodeUTF8))
        self._lbl_storage_usage.setText(QtGui.QApplication.translate("UserDetails", "Speicherverbrauch", None, QtGui.QApplication.UnicodeUTF8))
        self._lbl_objects.setText(QtGui.QApplication.translate("UserDetails", "Objekte", None, QtGui.QApplication.UnicodeUTF8))
        self._access_rights_box.setTitle(QtGui.QApplication.translate("UserDetails", "Zugriffsrechte", None, QtGui.QApplication.UnicodeUTF8))
        self._lbl_role.setText(QtGui.QApplication.translate("UserDetails", "Rollen", None, QtGui.QApplication.UnicodeUTF8))
        self._lbl_role_owner.setText(QtGui.QApplication.translate("UserDetails", "Rolleninhaber", None, QtGui.QApplication.UnicodeUTF8))
        self._lbl_authorized_actions.setText(QtGui.QApplication.translate("UserDetails", "Erlaubte Aktionen", None, QtGui.QApplication.UnicodeUTF8))
        self._lbl_owner.setText(QtGui.QApplication.translate("UserDetails", "Eigentümer", None, QtGui.QApplication.UnicodeUTF8))
        self._lbl_manager.setText(QtGui.QApplication.translate("UserDetails", "Manager", None, QtGui.QApplication.UnicodeUTF8))
        self._lbl_other.setText(QtGui.QApplication.translate("UserDetails", "Andere", None, QtGui.QApplication.UnicodeUTF8))
        self._user_info_tabs.setTabText(self._user_info_tabs.indexOf(self._account_tab), QtGui.QApplication.translate("UserDetails", "Konto", None, QtGui.QApplication.UnicodeUTF8))
        self._phone_box.setTitle(QtGui.QApplication.translate("UserDetails", "Telefon/Fax", None, QtGui.QApplication.UnicodeUTF8))
        self._lbl_private_tel.setText(QtGui.QApplication.translate("UserDetails", "Privat", None, QtGui.QApplication.UnicodeUTF8))
        self._lbl_mobile_tel.setText(QtGui.QApplication.translate("UserDetails", "Mobil", None, QtGui.QApplication.UnicodeUTF8))
        self._lbl_office_tel.setText(QtGui.QApplication.translate("UserDetails", "Büro", None, QtGui.QApplication.UnicodeUTF8))
        self._lbl_fax.setText(QtGui.QApplication.translate("UserDetails", "Fax", None, QtGui.QApplication.UnicodeUTF8))
        self._lbl_language.setText(QtGui.QApplication.translate("UserDetails", "Sprache", None, QtGui.QApplication.UnicodeUTF8))
        self._lbl_organisation.setText(QtGui.QApplication.translate("UserDetails", "Organisation", None, QtGui.QApplication.UnicodeUTF8))
        self._lbl_office_url.setText(QtGui.QApplication.translate("UserDetails", "Webseite (Büro)", None, QtGui.QApplication.UnicodeUTF8))
        self._lbl_private_url.setText(QtGui.QApplication.translate("UserDetails", "Webseite (privat)", None, QtGui.QApplication.UnicodeUTF8))
        self._lbl_address.setText(QtGui.QApplication.translate("UserDetails", "Adresse", None, QtGui.QApplication.UnicodeUTF8))
        self._lbl_instant_messenger.setText(QtGui.QApplication.translate("UserDetails", "Instant Messenger", None, QtGui.QApplication.UnicodeUTF8))
        self._lbl_more_info.setText(QtGui.QApplication.translate("UserDetails", "Weitere Informationen", None, QtGui.QApplication.UnicodeUTF8))
        self._user_info_tabs.setTabText(self._user_info_tabs.indexOf(self._personal_tab), QtGui.QApplication.translate("UserDetails", "Persönliches", None, QtGui.QApplication.UnicodeUTF8))
        self._user_info_tabs.setTabText(self._user_info_tabs.indexOf(self._pic_tab), QtGui.QApplication.translate("UserDetails", "Bild", None, QtGui.QApplication.UnicodeUTF8))

